language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
dist: xenial
addons:
  apt:
    packages:
    - cmake
# command to install dependencies
cache:
  - pip
install:
  - "pip install --upgrade pip; pip install --upgrade setuptools; pip install -r test_requirements.txt; pip install -e git+https://github.com/django/django-contrib-comments.git#egg=django-contrib-comments; python setup.py install"
# command to run tests
env:
  - TESTCASE=tests/tests_docs.py
  - TESTCASE=tests/test_handler.py
  - TESTCASE=tests/tests_middleware.py
  - TESTCASE=tests/tests_placebo.py
  - TESTCASE=tests/tests_async.py
  - TESTCASE=tests/tests.py
before_script:
  - make flake
script:
  - make test-case
    #  - coverage combine --append
after_success:
  coveralls
notifications:
  slack: zappateam:TTJ0mfHunDK0IBweKkEXjGpR
